spring:
  application:
    name: restfulweb
  datasource:
    url: jdbc:mysql://localhost:3306/m03restful
    username: m03
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
